version: "2.0"

services:
  #PHP
  app:
    build: .
    image: php:7.2-fpm
    container_name: blog
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      APP: blog
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
      - ./docker/local.ini:/usr/local/etc/php/conf.d/local.ini
    links:
      - db

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=project.local
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    command: [nginx-debug, "-g", "daemon off;"]

  #MySQL Service
  db:
    image: postgres:11-alpine
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: wilcox
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /Users/wilcoxmarin/WilcoxMarin/VolumenesDocker/postgres11:/var/lib/mysql/
